[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "cof-simu"
version = "0.0.1"
requires-python = ">=3.12"

[tool.setuptools.packages.find]
where = ["src"]
